# Render Blueprint for Django + Gunicorn
services:
  - type: web
    name: meter-soap-server
    env: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:      
    - key: DATABASE_URL    
      fromDatabase:
        name: meterdb
        property: connectionString
    - key: SECRET_KEY
      generateValue: true
    - key: WEB_CONCURRENCY
      value: 4
